### ISSUE TITLE
But where’s the code?

### ISSUE THREAD

**Issue by jamesfoster** [chwoerz/advanced-typescript#1]
Loved the talk. Too much to remember 🤣 is there a link to samples of what you talked about?

**Comment by chwoerz** [comment]
Thanks so much 
https://github.com/typed-rocks/typescript It’s here :)

**Comment by jamesfoster** [comment]
@chwoerz Hey, I took a look at your samples and came up with this which is now in our product :D 

https://github.com/jamesfoster/advanced-typescript/blob/main/uri-template.ts

I've since come across Michigan TypeScript and seen the crazy stuff they're doing.

https://www.youtube.com/watch?v=4Eh-F78Y2Pg

I'm thinking of writing this again using HKT toolbelt just for giggles. :D
